# Generated by Django 5.1.4 on 2025-01-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_product_categories_product_most_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='game_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
