# Generated by Django 5.1.4 on 2025-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='game_images/default.jpg', upload_to='game_images/'),
        ),
    ]
