# Generated by Django 5.1.4 on 2025-02-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0021_playerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
