# Generated by Django 5.1.4 on 2025-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_remove_library_purchased_at_library_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='player.library'),
        ),
    ]
