# Generated by Django 5.1.4 on 2025-02-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0030_profile_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='IMG/man_default.png', upload_to='avatars/'),
        ),
    ]
