# Generated by Django 5.1.4 on 2025-02-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
