# Generated by Django 5.1.4 on 2025-01-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_profile_address_profile_age_profile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('downloads', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
