# Generated by Django 5.1.4 on 2025-02-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_rename_name_game_genre_remove_game_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='game',
        ),
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='purchasedproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='most_played',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending_game',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('adv', 'Adventure'), ('str', 'Strategy'), ('rac', 'Racing'), ('act', 'Action'), ('sim', 'Simulation')], default='adv', max_length=100),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PurchasedProduct',
        ),
    ]
