# Generated by Django 5.1.4 on 2025-02-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_player_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='player_library',
        ),
    ]
