# Generated by Django 5.1.4 on 2025-02-10 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0028_downloadedgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='purchased_at',
        ),
        migrations.AddField(
            model_name='library',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DownloadedGame',
        ),
    ]
