# Generated by Django 5.1.4 on 2025-02-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0031_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='username',
        ),
    ]
