# Generated by Django 5.1.4 on 2025-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0033_product_game_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('adv', 'Phiêu lưu'), ('str', 'Kinh dị'), ('rac', 'Đua xe'), ('act', 'Hành động'), ('sim', 'Giả lập')], default='adv', max_length=100),
        ),
    ]
